### ISSUE TITLE
Question about logging in

### ISSUE THREAD

**Issue by DanCarterGMSL** [paulbulman/parking-website#78]
If I've not been to the parking website in the last day or so I'm prompted to log in. It used to keep you logged in for a lot longer. Is this a new security feature?

**Comment by paulbulman** [comment]
Yeah, I'm not aware of a reliable way with Cognito/Amplify (or maybe it's common to any JWT-based auth) to have a "Stay logged in" option when logging in. So given that there's no guarantee people are using a non-shared device, or will explicitly log themselves out when they're finished, defaulting to staying logged in for much longer than that didn't seem a great idea. I've found it pretty painless given a password manager, but open to other suggestions 🙂

**Comment by DanCarterGMSL** [comment]
Sounds like a sensible idea! As it's against my home email address I've stored the password in my home password manager which isn't logged in on my work PC, so it's a little annoying but I can live with it.
